"""
Web port of the Hashavshevet (חשבשבת) accounting export — Code VB6/
frmReset1.frm's Public Sub Reset(ResetNr As Long) writes a movein.dat file
whenever a reset is committed OR resent (frmSendtoHash.frm re-running
Reset() against an archived ResetNr<>0, "resend to Hashavshevet").

This module's `build_movein_dat()` implements the SECOND path: regenerating
movein.dat for an ALREADY-ARCHIVED reset (ResetNr<>0), on demand from either
the past-reset lookup screen or the "העברה לחשבשבת" (Transfer to
Hashavshevת) screen — both call routers/reset.py's download_movein_dat().
It reads straight from Invoices/Checks/BadChecks rows already stamped with
that ResetNr — matches the original's re-query (`select * from Invoices
where ResetNr = <n> and Area=<area>`) exactly, since this app's invoice
rows keep their ResetNr permanently once stamped.

WHERE THE FILE ACTUALLY GETS WRITTEN: nowhere on the backend's own
filesystem — the generated bytes are returned as a plain HTTP download.
Confirmed 2026-09-27 that whoever triggers this always does so from a
browser running ON the accounting PC itself (the same machine that then
runs ipus/ipusim to actually import the file into Hashavshevת), so the
browser's own download IS the delivery — no backend-side network push to a
remote machine is needed. (A `write_movein_file()`/file-bridge mechanism
existed briefly for a backend-push scenario that turned out not to apply
here, and was removed.) In practice: point that browser's default download
folder at CFG.hdir's real value (e.g. "C:\hmon12" — the original's own
resend destination, frmReset1.frm ~line 1427-1428) instead of the usual
Downloads folder.

The FIRST path (a brand-new reset, ResetNr=0 at generation time) is NOT
implemented here at all — confirmed 2026-09-27 via frmSendtoHash.frm that
the real workflow never generates movein.dat automatically at commit time
in practice; it's only ever generated on demand, later, through one of the
two screens above. This app's own commit_reset() (routers/reset.py) simply
stamps ResetNr onto the relevant Invoices/Checks rows and stops there.

Reverse-engineered from frmReset1.frm (source stored in CP862/DOS-Hebrew,
confirmed by decoding raw literal bytes) via two research passes
(2026-09-25): one over the movein.dat *print* block (~line 1430-2033), one
over the aggregation logic that feeds it (~line 798-1417).

VALIDATED (2026-09-26) via real byte-diffs against actual old-software
movein.dat exports for two live resets (33727, 33733): all narration
literals (sales, bank name, cash, kupa/hachnasot, delayed-check, bad-check,
credit-note, paid-check-reversal), the header, and every fixed-width field
now match the real export exactly for the record types exercised by those
two resets. Area 9 (Netanya)'s branch name is confirmed to be genuinely
garbled in the REAL old software's own output too (not a bug introduced
here) — see `_SNIF_NAME` below.

ONE INTENTIONAL, KNOWING DEVIATION from the legacy export (approved by the
user 2026-09-26): VAT-rate lookup. See the `act_vat` comment inside
`build_movein_dat()` for the real VB6 source proving the original computes
VAT using the CURRENT/live CFG.VAT rate for every invoice in a reset,
regardless of what rate was actually charged when each invoice was issued —
a real bug in the original whenever VAT changes between an invoice's issue
date and its reset. This app instead uses each invoice's own stored `Vat`
rate, which the user confirmed is the behavior they want going forward,
even though it means this app's export will differ from the legacy one
whenever that specific bug would otherwise have been triggered.

KNOWN, ACCEPTED RESIDUAL DIFFERENCE (investigated 2026-09-26, ResetNr 33733):
isolated per-price-code sales lines can differ from the real legacy export
by exactly 1 agora (always the real export being 1 agora LOWER, never
higher). Root-caused via a debug trace of the real DB rows (not
hand-transcribed data) confirming this is NOT an invoice-inclusion bug and
NOT the VAT-source deviation above -- three independent single-invoice
cases (sub_total 30.0, 55.0, 2150.0, all act_vat=18) were hand-verified
against `temp_vat = Int(sub_total*100*act_vat/(100+act_vat)) / 100; net =
sub_total - temp_vat; Int(net*100)` using plain 64-bit double, 80-bit
extended precision, AND exact decimal arithmetic -- all three agree with
THIS app's output, not the real export's, and no whole-number VAT rate
reproduces the real export's values either. The consistent "-1 agora,
independent of magnitude" pattern is the signature of the original
Intel-x87-FPU 80-bit-extended-register rounding path (historic VB6/native
code on x86) diverging from strict IEEE-754 double arithmetic in a way
that isn't practically reproducible without emulating x87 register
semantics instruction-by-instruction. Accepted as-is per user decision
(2026-09-26) -- this app's arithmetic is, if anything, the more
mathematically correct of the two.

STILL OPEN / NOT YET VALIDATED — record types not exercised by either test
reset so far:

- Three `_SNIF_NAME` values (areas 1/3/6) contain a literal, unrecoverable
  "?" in the VB6 source itself (presumably historical data corruption) —
  reproduced here exactly as found, not guessed at. Areas 2 (Jerusalem) and
  7 (Eilat) were flagged by VB6-source research as having the same kind of
  mixed-codepage literal that turned out to be genuinely garbled for area
  9 — they may exhibit the same real-software garbling, unconfirmed absent
  a real reset from either branch to diff against.
- "מזומן המחאות" (cash-checks deposit summary, record type 4) hasn't
  appeared in either test reset — untested.
- `cash` (record type 7, "מזומן") accumulation on payment_type==1 is
  inferred by analogy to this app's own routers/reset.py (same
  payment_type==1 -> cash pattern used there) since the exact VB6 quote for
  this specific line wasn't captured by either research pass.
- Credit-card payment dates (record type 3) use `main_deposit_date` for
  every payment rather than the original's per-bank/Isracard deposit-cycle
  date tables (init_credit_deposit_dates in frmReset1.frm) — that table's
  exact bank-cycle math wasn't captured either. Only affects the `yymm`/
  `ddmmyy` fields on credit-card lines, not any amount.
- Line-interior padding (the exact count of trailing spaces before a line
  hits 178 chars) is computed here by measuring everything else and padding
  the remainder, rather than copying the VB6 source's literal spacing
  character-for-character in every case — the numeric/GL-account content
  should be right, but padding width inside a field very rarely also
  matters to Hashavshevת parsing, so this is flagged for awareness, not as
  a known bug.

Every emitted line is asserted to be exactly LINE_WIDTH characters before
being added to the file — a bug in any of the fixed-width numeric fields
above will raise instead of silently producing a malformed file.
"""
from __future__ import annotations

from datetime import date, datetime
from typing import Optional

from sqlalchemy.orm import Session

from .models import (
    BadChecks,
    CREDIT_NOTE,
    HESHBONIT,
    HESHBONIT_KABALA,
    Invoice,
    KABALA,
    PriceListEilat,
    PriceListItem,
)
from .models import Reset as ResetRow

LINE_WIDTH = 178
EILAT_AREA = 7

# DepositBank (0/1/2, ResetModal.tsx's DEPO_BANKS) -> (cartis, cartis_delayed)
# deposit-slip constants — frmReset1.frm ~line 1000-1010.
_CARTIS_BY_BANK = {0: (1360005, 136), 1: (1450001, 145)}
_CARTIS_DEFAULT = (1350005, 135)  # DepositBank not in {0, 1}

# Branch-name narration for the per-branch "kupa" closing lines (record type
# 10), and each branch's own GL sub-account — Select Case ResetArea,
# frmReset1.frm ~line 1900-1933. Areas 1/3/6 contain a literal unrecoverable
# "?" in the VB6 source itself. All values are exactly 7 chars wide.
_SNIF_NAME = {
    # Leading spaces confirmed to stay in place (not swept to the end) --
    # same lesson as the cash-line narration fix: only the actual Hebrew
    # content run reverses, padding spaces don't move. Fixed 2026-09-26
    # after this exact space-position mistake was caught via a real
    # ResetNr 33733 byte-diff on a different field.
    0: "  ןולוח",
    1: "    פצ?",
    # Area 2 (Jerusalem): NOT a readable Hebrew string, same root cause as
    # area 9 below. Confirmed via raw byte extraction from a real ResetNr
    # 33627 export (2026-09-26) -- bytes ed e9 ec f9 e5 f8 e9, which are
    # "ירושלים" correctly encoded in cp1255 but get decoded under this
    # file's actual cp862 encoding, producing the garbled literal below.
    # Reproduced byte-for-byte, not "corrected" to readable Hebrew.
    2: "φΘ∞∙σ°Θ",
    3: " אשק?ון",
    4: "   הפיח",
    5: "עבש ראב",
    6: "  הפו?ע",
    # Area 7 (Eilat): NOT a readable Hebrew string, same root cause as
    # areas 2/9 below. Confirmed via raw byte extraction from a real
    # ResetNr 33525 export (2026-09-26) -- bytes e0 e9 ec fa, which are
    # "אילת" correctly encoded in cp1255 but decoded here under this file's
    # actual cp862 encoding, producing the garbled literal below.
    # Reproduced byte-for-byte, not "corrected" to readable Hebrew. Note
    # this is only 4 chars wide (not 7 like the other areas) -- confirmed
    # from the real export's own field width, not padded/guessed.
    7: "   αΘ∞·",
    # Area 9 (Netanya): NOT a readable Hebrew string. Confirmed via raw
    # byte extraction from a real ResetNr 33733 export (2026-09-26) that the
    # real old software's own output for this branch is genuinely garbled
    # -- bytes e4 e9 f0 fa f0, which decode under cp862 to the literal
    # characters below (not valid Hebrew at all). This traces back to the
    # VB6 source itself storing this literal in a different codepage
    # (cp1255) than the rest of the file (cp862) -- see module docstring.
    # Reproduced byte-for-byte here rather than "corrected" to readable
    # Hebrew, since matching the real export's actual bytes is the point.
    9: "  ΣΘ≡·≡",
}
_KUPA_SNIF = {0: 1110013, 1: 1110012, 2: 1110012, 3: 1110012, 4: 1110015, 5: 1110018, 6: 1110018, 7: 1110017, 9: 1110019}

# Credit-card bank narration — only slot 0 (Visa/"הזיו") ever accumulates
# money in this build; multi-bank routing (Isracard/Diners/Amex) is dead
# code in the live form (see routers/reset.py's module docstring). All 4
# slots share GL sub-account 123.
_BANK_NUMBER_CREDIT = 123


def _rj(value: object, width: int) -> str:
    s = str(value)
    if len(s) > width:
        raise ValueError(f"movein.dat field overflow: {value!r} does not fit width {width}")
    return s.rjust(width)


def _vb_str(n: float) -> str:
    """VB6's Str(n) — a leading space for n>=0, none for negative."""
    i = int(n)
    return f" {i}" if i >= 0 else str(i)


def _ddmmyy(d: Optional[date]) -> str:
    return d.strftime("%d%m%y") if d else "000000"


def _yymm(d: Optional[date]) -> str:
    return d.strftime("%y%m") if d else "0000"


def _pad_line(prefix: str) -> str:
    """Pad `prefix` with trailing spaces to exactly LINE_WIDTH, or raise if it's already too long."""
    if len(prefix) > LINE_WIDTH:
        raise ValueError(f"movein.dat line overflow ({len(prefix)} > {LINE_WIDTH}): {prefix!r}")
    line = prefix + " " * (LINE_WIDTH - len(prefix))
    assert len(line) == LINE_WIDTH
    return line


def _parse_slot_date(raw: Optional[str]) -> Optional[date]:
    """
    CheckDateN is usually stored 'DD/MM/YYYY' (matches routers/reset.py's
    _parse_due_date), but the real VB6 source (frmReset1.frm ~line 1228:
    `CDate(Replace(InvRec.Recordset![CheckDate1], ".", "/"))`) normalizes
    '.'-separated dates too -- some older rows apparently use dots.
    Confirmed as a real, live case (2026-09-26): a ResetNr 33631 check with
    a dot-separated CheckDateN silently failed to parse under the
    slash-only version, defaulting to None -> misclassified as a delayed
    check instead of "cash now", which then also emitted the wrong record
    type entirely (record type 5 instead of the cash-checks-summary record
    type 4) -- confirmed via a real byte-diff against the actual
    old-software export for that reset.
    """
    if not raw:
        return None
    normalized = raw.strip().replace(".", "/")
    try:
        return datetime.strptime(normalized, "%d/%m/%Y").date()
    except ValueError:
        return None


def _cc_number(raw: Optional[str]) -> Optional[int]:
    """cc_nr = Mid(CCNrN, 1, 5), card_number = Val(cc_nr)."""
    if not raw:
        return None
    try:
        return int(raw.strip()[:5])
    except ValueError:
        return None


def build_movein_dat(db: Session, reset_row: ResetRow, debug_trace: Optional[list] = None) -> bytes:
    """
    Builds the full movein.dat content for an already-archived reset, as
    CP862 bytes (matches the VB6 source file's own storage encoding — see
    module docstring). Raises ValueError if any field/line width is wrong,
    rather than emitting a malformed file.

    `debug_trace`, if a list is passed in, gets one dict appended per
    Code1-6 line item processed by the cards() loop below — used only by
    the /movein.dat?debug=1 endpoint to get exact ground truth on which
    invoices/amounts feed a given card, instead of hand-transcribing DB
    rows into chat (which is error-prone and was the suspected source of
    an unexplained 1-agora mismatch investigation on 2026-09-26).
    """
    reset_nr = reset_row.ResetNr
    area = reset_row.Area
    main_deposit_date = reset_row.DepositDate or reset_row.ResetDate
    print_date_str = _ddmmyy(reset_row.ResetDate)
    cartis, cartis_delayed = _CARTIS_BY_BANK.get(reset_row.DepoBank, _CARTIS_DEFAULT)

    # DELIBERATE DEVIATION (approved by user 2026-09-26): the real VB6
    # source (frmReset1.frm lines 1019-1020) sets `act_vat` from the
    # GLOBAL, LIVE `VAT` variable (loaded once from CFG.VAT at app
    # startup -- Account.frm: `VAT = cfgRec.Recordset![VAT]`), applying
    # the CURRENT config rate to every invoice in a reset regardless of
    # what rate was actually charged when each invoice was issued:
    #   If EILAT Then act_vat = 0 Else act_vat = VAT
    # This is a real bug in the original if the VAT rate is ever changed
    # between an invoice's issue date and the reset that later reads it --
    # confirmed via a real byte-diff (2026-09-26) showing selective
    # 1-agora mismatches on some price codes but not others in the same
    # reset, consistent with some invoices' snapshotted rate having
    # drifted from the live config. The user confirmed this is a genuine
    # old-software bug and asked this app to compute VAT correctly from
    # each invoice's OWN stored `Vat` rate instead of reproducing it --
    # so, unlike every other quirk in this module, this one is
    # INTENTIONALLY NOT byte-faithful to the legacy export whenever a VAT
    # change is involved.

    invoices = (
        db.query(Invoice)
        .filter(
            Invoice.ResetNr == reset_nr,
            Invoice.Area == area,
            (Invoice.Deleted == False) | (Invoice.Deleted.is_(None)),  # noqa: E712
        )
        .order_by(Invoice.InvNr)
        .all()
    )

    # --- accumulators (all start at 0 — frmReset1.frm lines 898-929) ---
    cards: dict[int, dict] = {}  # Code -> {"acc_number": int|None, "money": float}
    first_inv_number: Optional[int] = None
    last_inv_number = 0
    last_inv_date: Optional[date] = None
    tot_total_kupa = 0.0
    total_credit = 0.0  # gross CREDIT_NOTE total, accumulated in the cards loop
    total_vat = 0.0  # running VAT across the cards loop
    temp_vat_last = 0.0  # last per-line VAT value seen in the cards loop —
    # reproduces the original reading a loop-scratch variable AFTER the loop
    # ends (same read-after-loop pattern already flagged/fixed for
    # ResetPreviewOut.totalVat in routers/reset.py; here it's kept as-is
    # since the goal is byte-fidelity with the legacy export, not a fix).
    cash = 0.0
    credit_card_payments = {0: 0.0, 1: 0.0, 6: 0.0}  # j -> cents; only j in {0,1,6} ever written
    credit_card_numbers: dict[int, Optional[int]] = {0: None, 1: None, 6: None}
    cash_checks_buckets: list[float] = []  # 7-per-bucket, money units (not cents)
    cash_check_running = 0
    delayed_check_lines: list[dict] = []
    paid_check_reversal_lines: list[dict] = []

    for inv in invoices:
        act_vat = 0 if inv.Eilat else (inv.Vat or 0)

        if inv.Type in (HESHBONIT_KABALA, HESHBONIT):
            nr = (inv.InvNr or 0) % 1_000_000
            if first_inv_number is None:
                first_inv_number = nr
            if nr >= last_inv_number:
                last_inv_number = nr
                last_inv_date = inv.Date

        if inv.Type in (HESHBONIT_KABALA, HESHBONIT, CREDIT_NOTE):
            for i in range(1, 7):
                code = getattr(inv, f"Code{i}")
                if not code:
                    # `If Code = 0 Then Exit For` (frmReset1.frm ~line 1135)
                    # -- NOT a "skip this empty slot and keep checking later
                    # ones". The original bails out of the WHOLE per-line
                    # loop the moment it hits a gap, so a later non-empty
                    # slot (e.g. Code3 set while Code1/Code2 are empty)
                    # never gets counted at all. Confirmed as the real cause
                    # of a real byte-diff mismatch (2026-09-26) -- this app
                    # was using `continue` here, which kept scanning past
                    # gaps and double-picked-up line items the original
                    # silently drops.
                    break
                sub_total = getattr(inv, f"SubTotal{i}") or 0
                line_vat = int(sub_total * 100 * act_vat / (100 + act_vat)) / 100 if act_vat else 0.0
                temp_vat_last = line_vat
                net = sub_total - line_vat
                bucket = cards.setdefault(code, {"acc_number": None, "money": 0.0})
                if bucket["acc_number"] is None:
                    # `If Area=7 Then PriceListEilat Else If EILAT Then
                    # PriceListEilat Else PriceList` (frmReset1.frm ~1139) --
                    # checks the invoice's numeric Area against EILAT_AREA
                    # too, not just the Eilat boolean flag alone.
                    use_eilat_table = inv.Area == EILAT_AREA or inv.Eilat
                    price_item = (db.get(PriceListEilat, code) if use_eilat_table else db.get(PriceListItem, code)) or (
                        db.get(PriceListItem, code) or db.get(PriceListEilat, code)
                    )
                    bucket["acc_number"] = getattr(price_item, "AccNr", None) if price_item else None
                if inv.Type == CREDIT_NOTE:
                    bucket["money"] -= net
                    total_credit += sub_total
                    total_vat -= line_vat
                else:
                    bucket["money"] += net
                    tot_total_kupa += sub_total
                    total_vat += line_vat

                if debug_trace is not None:
                    debug_trace.append(
                        {
                            "inv_nr": inv.InvNr,
                            "type": inv.Type,
                            "slot": i,
                            "code": code,
                            "acc_number": bucket["acc_number"],
                            "sub_total": sub_total,
                            "act_vat": act_vat,
                            "line_vat": line_vat,
                            "net": net,
                            "money_running_total": bucket["money"],
                        }
                    )

        if inv.Type in (HESHBONIT_KABALA, KABALA) and (inv.IgnoreInReset or 0) != 1:
            for i in range(1, 7):
                payment_type = getattr(inv, f"PaymentType{i}")
                money = getattr(inv, f"Money{i}") or 0
                if not payment_type:
                    continue
                if payment_type == 1:
                    cash += int(money * 100)
                elif payment_type == 2:
                    raw_check_date = getattr(inv, f"CheckDate{i}")
                    check_date = _parse_slot_date(raw_check_date)
                    is_cash_now = check_date is not None and main_deposit_date is not None and main_deposit_date >= check_date
                    if debug_trace is not None:
                        debug_trace.append(
                            {
                                "kind": "check",
                                "inv_nr": inv.InvNr,
                                "slot": i,
                                "raw_check_date": raw_check_date,
                                "parsed_check_date": check_date.isoformat() if check_date else None,
                                "main_deposit_date": main_deposit_date.isoformat() if main_deposit_date else None,
                                "is_cash_now": is_cash_now,
                                "money": money,
                            }
                        )
                    if is_cash_now:
                        bucket_i = cash_check_running // 7
                        cash_check_running += 1
                        while len(cash_checks_buckets) <= bucket_i:
                            cash_checks_buckets.append(0.0)
                        cash_checks_buckets[bucket_i] += money
                    else:
                        delayed_check_lines.append(
                            {
                                "check_nr": getattr(inv, f"CheckNr{i}") or 0,
                                "inv_nr": inv.InvNr or 0,
                                "check_date": check_date,
                                "money": money,
                            }
                        )
                elif payment_type == 3:
                    credit_card_payments[0] += int(money * 100)
                    credit_card_numbers[0] = _cc_number(getattr(inv, f"CCNr{i}"))
                elif payment_type == 4:
                    credit_card_payments[6] += int(money * 100)
                    credit_card_numbers[6] = _cc_number(getattr(inv, f"CCNr{i}"))
                elif payment_type == 5:
                    credit_card_payments[1] += int(money * 100)
                    credit_card_numbers[1] = _cc_number(getattr(inv, f"CCNr{i}"))

        if inv.Type == KABALA and (inv.IgnoreInReset or 0) == 1:
            org_date = _parse_slot_date(inv.CheckDate2)
            if org_date is not None:
                paid_check_reversal_lines.append(
                    {
                        "check_nr2": inv.CheckNr2 or 0,
                        "taxi_nr": inv.TaxiNr or 0,
                        "family_name": (inv.FamilyName or "").strip(),
                        "org_date": org_date,
                        "money1": inv.Money1 or 0,
                    }
                )
                cash += int((inv.Money1 or 0) * 100)

    if first_inv_number is None:
        first_inv_number = 0
    if last_inv_date is None:
        last_inv_date = reset_row.ResetDate

    tot_total_kupa -= total_credit  # frmReset1.frm line ~1752
    net_total_kupa = sum(int(c["money"] * 100) for c in cards.values())

    lines: list[str] = []

    # --- 1. header ---
    lines.append(_pad_line("  0"))

    # --- 2. per-account sales lines ("סקטינומ תוריכמ") ---
    for entry in cards.values():
        money = entry["money"]
        temp_card = int(money * 100)
        plus = " " if money < 0 else "+"
        acc_number = entry["acc_number"] if entry["acc_number"] is not None else 0
        prefix = (
            "   "
            + _rj(first_inv_number % 100000, 5)
            + print_date_str
            + _rj(last_inv_number % 100000, 5)
            + _ddmmyy(last_inv_date)
            + "  $        "
            + "סקטינומ תוריכמ"
            + " " * 17
            + _rj(acc_number, 7)
            + " " * 32
            + plus
            + _rj(temp_card, 11)
        )
        lines.append(_pad_line(prefix))

    # --- 3. credit-card payment lines ---
    for j in (0, 1, 6):
        money_cents = credit_card_payments[j]
        if money_cents == 0:
            continue
        card_number = credit_card_numbers[j] or 0
        prefix = (
            "   "
            + _rj(card_number, 5)
            + print_date_str
            + _rj(last_inv_number % 100000, 5)
            + _ddmmyy(main_deposit_date)
            + "  $"
            + _rj("הזיו", 22)
            + _rj(_BANK_NUMBER_CREDIT, 4)
            + _yymm(main_deposit_date)
            + " " * 24
            + "+"
            + _rj(int(money_cents), 11)
        )
        lines.append(_pad_line(prefix))

    # --- 4. cash-checks deposit summary lines ---
    for bucket_total in cash_checks_buckets:
        if bucket_total == 0:
            continue
        prefix = (
            "   99999"
            + print_date_str
            + "99999"
            + _ddmmyy(main_deposit_date)
            + "  $          "
            + "תואחמה ןמוזמ"
            + _rj(cartis, 8)
            + " " * 24
            + "+"
            + _rj(int(bucket_total * 100), 11)
        )
        lines.append(_pad_line(prefix))

    # --- 5. delayed-check lines ("יוחד.חמה") ---
    for dc in delayed_check_lines:
        prefix = (
            "   "
            + _rj(dc["check_nr"] % 100000, 5)
            + print_date_str
            + _rj(dc["inv_nr"] % 100000, 5)
            + _ddmmyy(dc["check_date"])
            + "  $"
            + _rj("יוחד.חמה", 22)
            + _rj(cartis_delayed, 4)
            + _yymm(dc["check_date"])
            + " " * 24
            + "+"
            + _rj(int(dc["money"] * 100), 11)
        )
        lines.append(_pad_line(prefix))

    # --- 6. paid-check reversal lines (" רזוח/קש.ש? ... 1100023") ---
    for pr in paid_check_reversal_lines:
        prefix = (
            "   "
            + _rj(pr["check_nr2"] % 100000, 5)
            + print_date_str
            + _rj(pr["taxi_nr"], 5)
            + _ddmmyy(pr["org_date"])
            + "  $"
            + _rj(pr["family_name"][-11:], 11)
            + " רזוח/קש.ש?                 1100023"
            + " " * 33
            + "+"
            + _rj(int(pr["money1"] * 100), 11)
        )
        lines.append(_pad_line(prefix))

    # --- 7. cash deposit line ("מזומן") ---
    if cash > 0:
        prefix = (
            "   "
            + _rj(first_inv_number % 100000, 5)
            + print_date_str
            + _rj(last_inv_number % 100000, 5)
            + _ddmmyy(main_deposit_date)
            + "  $                 "
            + "ןמוזמ "
            + _rj(cartis, 7)
            + " " * 24
            + "+"
            + _rj(_vb_str(cash), 11)
        )
        lines.append(_pad_line(prefix))

    # --- 8/9. kupa + hachnasot-bemaavar lines (only if tot_total_kupa != 0) ---
    if tot_total_kupa != 0:
        plus8 = " " if tot_total_kupa < 0 else "+"
        if area == 7:  # Eilat
            prefix = (
                "   "
                + _rj(first_inv_number % 100000, 5)
                + print_date_str
                + _rj(last_inv_number % 100000, 5)
                + _ddmmyy(last_inv_date)
                + "  $            "
                + "רבעמב הפוק"
                + " 1110021         4520101"
                + "        +"
                + _rj(int(tot_total_kupa * 100), 11)
                + " " * 12
                + plus8
                + _rj(int(tot_total_kupa * 100 - temp_vat_last * 100), 11)
                + "+"
                + _rj(int(temp_vat_last * 100), 11)
            )
            total_vat_for_hachnasot = int(temp_vat_last * 100)
        else:
            total_vat_local = int(temp_vat_last * 100)  # `total_vat = temp_vat * 100` — see module docstring re: this overwrite
            prefix = (
                " לח"
                + _rj(first_inv_number % 100000, 5)
                + print_date_str
                + _rj(last_inv_number % 100000, 5)
                + _ddmmyy(last_inv_date)
                + "  $            "
                + "רבעמב הפוק"
                + " 1110020         4520100"
                + " 3110046+"
                + _rj(int(tot_total_kupa * 100), 11)
                + " " * 12
                + plus8
                + _rj(int(tot_total_kupa * 100) - total_vat_local, 11)
                + "+"
                + _rj(total_vat_local, 11)
            )
            total_vat_for_hachnasot = total_vat_local
        lines.append(_pad_line(prefix))

        plus9 = "+" if tot_total_kupa < 0 else "-"
        if area == 7:
            prefix_a = (
                "   "
                + _rj(first_inv_number % 100000, 5)
                + print_date_str
                + _rj(last_inv_number % 100000, 5)
                + print_date_str
                + "  $            רבעמב הפוק"
                + " 1110021                        "
                + plus9
                + _rj(int(tot_total_kupa * 100), 11)
            )
            lines.append(_pad_line(prefix_a))
            prefix_b = (
                "   "
                + _rj(first_inv_number % 100000, 5)
                + print_date_str
                + _rj(last_inv_number % 100000, 5)
                + _ddmmyy(last_inv_date)
                + "  $          רבעמב תוסנכה                "
                + " 4520101                                "
                + plus9
                + _rj(int(tot_total_kupa * 100), 11)
            )
            lines.append(_pad_line(prefix_b))
        else:
            prefix_a = (
                "   "
                + _rj(first_inv_number % 100000, 5)
                + print_date_str
                + _rj(last_inv_number % 100000, 5)
                + print_date_str
                + "  $            רבעמב הפוק"
                + " 1110020                        "
                + plus9
                + _rj(int(tot_total_kupa * 100), 11)
            )
            lines.append(_pad_line(prefix_a))
            prefix_b = (
                "   "
                + _rj(first_inv_number % 100000, 5)
                + print_date_str
                + _rj(last_inv_number % 100000, 5)
                + _ddmmyy(last_inv_date)
                + "  $          רבעמב תוסנכה                "
                + " 4520100                                "
                + plus9
                + _rj(int(tot_total_kupa * 100) - total_vat_for_hachnasot, 11)
            )
            lines.append(_pad_line(prefix_b))

    # --- 10. per-branch (snif) closing lines — always, regardless of tot_total_kupa ---
    snif_name = _SNIF_NAME.get(area, f"אזור {area}"[:7].rjust(7))
    kupa_snif = _KUPA_SNIF.get(area, 0)
    plus10 = "-" if tot_total_kupa < 0 else "+"
    prefix_a = (
        "   "
        + _rj(first_inv_number % 100000, 5)
        + print_date_str
        + _rj(last_inv_number % 100000, 5)
        + print_date_str
        + "  $          "
        + snif_name
        + " הפוק"
        + _rj(kupa_snif, 8)
        + " " * 24
        + plus10
        + _rj(int(tot_total_kupa * 100), 11)
    )
    lines.append(_pad_line(prefix_a))
    prefix_b = (
        "   "
        + _rj(first_inv_number % 100000, 5)
        + print_date_str
        + _rj(last_inv_number % 100000, 5)
        + print_date_str
        + "  $          "
        + snif_name
        + " הפוק                "
        + _rj(kupa_snif, 8)
        + " " * 32
        + plus10
        + _rj(int(tot_total_kupa * 100), 11)
    )
    lines.append(_pad_line(prefix_b))

    # --- 11. bad-checks lines ("רזוח.חמה") — only Area 0 ---
    if area == 0:
        bad_checks = db.query(BadChecks).filter(BadChecks.ResetNr == reset_nr).order_by(BadChecks.BadCheckNr).all()
        for bc in bad_checks:
            bank_number = 1360005 if (bc.Bank or 0) == 0 else 1300002
            due = _parse_slot_date(bc.DueDate)
            money_cents = int((bc.Money or 0) * 100)
            prefix = (
                "   "
                + _rj((bc.CheckNr or 0) % 100000, 5)
                + print_date_str
                + _rj((bc.TaxiNr or 0) % 100000, 5)
                + _ddmmyy(due)
                + "  $"
                + "           "
                + "   רזוח.חמה 1100023        "
                + _rj(bank_number, 8)
                + "        +"
                + _rj(money_cents, 11)
                + "            +"
                + _rj(money_cents, 11)
            )
            lines.append(_pad_line(prefix))

    # --- 12. credit-note lines ("יוכיז.שח") ---
    for inv in invoices:
        if inv.Type != CREDIT_NOTE:
            continue
        gross = sum(getattr(inv, f"SubTotal{i}") or 0 for i in range(1, 7))
        prefix = (
            "   "
            + _rj((inv.RecNr or 0) % 100000, 5)
            + print_date_str
            + _rj(inv.TaxiNr or 0, 5)
            + _ddmmyy(inv.Date)
            + "  $"
            + "           "
            + "   יוכיז.שח                 3400017                                "
            + "+"
            + _rj(int(gross * 100), 11)
        )
        lines.append(_pad_line(prefix))

    content = "\r\n".join(lines) + "\r\n"
    return content.encode("cp862", errors="replace")
